version: "3"

services:
    app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app

    mongo:
        image: "mongo"
        ports:
            - '27017:27017' # configure your port
        volumes:
            - "mongodb:/data/db"

    redis:
        image: "redis"
        ports:
            - '6379:6379' # configure your port

volumes:
    mongodb:
        driver: local
